name: Node.js Package

on:
  push:
    branches: [ main ]
  # release:
    # types: [created]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: setup .npmrc file
        run: |
          cd ~
          touch .npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm publish
